### DISCUSSION TITLE
Can it figure out what my `$HOME` is?

### DISCUSSION THREAD

**Discussion by Raj2032** [tweag/nickel#1356] [Q&A]
Lets say if I wanted something like this in my `Cargo.toml` file:

```toml
[dependency]
some_lib = {path = "~/Desktop/some_lib"}
```

This is obviously not valid as it can't convert `~` to `/home/<username>/`.

So I was wondering if I understood correctly, would Nickel solve such an issue and actually create a `Cargo.toml` file by figuring out what is the `~` and then add this bit in: `/Desktop/some_lib` into the `Cargo.toml` file?
