### ISSUE TITLE
How to control a contract export?

### ISSUE THREAD

**Issue by rapenne-s** [tweag/nickel#1170]
**Describe the bug**

I'm trying to use Nickel to generate ansible playbooks snippets, I just want to define files and an action triggered if it changes. However, I can't figure how to do that with Nickel.

I created a contract with all the information I need, but I would like the export to be constructed to my needs instead of being the raw values passed in.

I have the following contract:

```
{
  File = 
  {
    src | Str,
    dest | Str,
    group | Str,
    mode | Str,
    command | Str,
    name | Str,
    token | Str,
  }
}
```

Used like this

```
let {File,..} = import "cfg.ncl" in
{
  files | Array File =
  [ 
    {
      src = "etc/dhcpd.conf",
      dest = "/" ++ src,
      group = "root",
      mode = "0640",
      name = "Dhcp configuration",
      command = "rcctl restart dhcpd",
      token = "dhcpd",
    },
  ]
}
```

and it produces the expected result

```
{
  "files": [
    {
      "command": "rcctl restart dhcpd",
      "dest": "/etc/dhcpd.conf",
      "group": "root",
      "mode": "0640",
      "name": "Dhcp configuration",
      "src": "etc/dhcpd.conf",
      "token": "dhcpd"
    }
  ]
}
```

However, I would like the output to look like this, but I don't know how to proceed :thinking: 

```yml
- name: Dhcp configuration file
  template:
    src: "etc/dhcpd.conf"
    dest: "/etc/dhcpd.conf"
    group: "root"
    mode: "0640"
  register: dhcpd

- name: Dhcp configuration action
  command: "rcctl restart dhcpd"
  when: dhcpd.changed
```
